# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: false
cache: packages
r:
  - bioc-release
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'
env:
  - LINTR_COMMENT_BOT=false
