# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: false
cache: packages
r:
  - bioc-release
r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
env:
  - LINTR_COMMENT_BOT=false
